### ISSUE TITLE
Object vs WildCard

### ISSUE THREAD

**Issue by joleneleee** [nus-cs2030/2021-s2#100]
When do you use object and when do you use wildcards in generics? Can you use them interchangeably?

**Comment by nicolaineo** [comment]
I believe that wildcards are encouraged because it makes code more readable and also, wildcards can have an upper or lower bound. 
List<? super SubType> works

**Comment by Qingyi1115** [comment]
Object and wildcards are not interchangeable. Object is something you can declare while using wildcards. Object is the most general type you can declare. It is as good as xxx<?>

**Comment by KaveenE** [comment]
ArrayList<?> is the same as ArrayList<? extends Object>.

ArrayList<?> is similar to ArrayList<Object> but there are some differences. ArrayList<Object> is invariant while ArrayList<?> is not.
Eg:
` ArrayList<Object> foo = new ArrayList<Integer>();` flags compilation warning whereas `ArrayList<?> foo = new ArrayList<Integer>(); ` doesn't

Another differences is for ArrayList<?>, you can't call a method that depends on the actual argument passed because `? `lets you pass in anything that at runtime, we don't what is actually passed. At most, you can only call method s that doesn't depend on the actual argument passed like `clear() `method of ArrayList or some method inherited from Object like `toString() `(since we know everything is a subtype of Object).

Eg: Try 
`ArrayList<?> foo = new ArrayList<Integer>()` 
` foo.add(2);`

You'll get an error

**Comment by joleneleee** [comment]
> ArrayList<?> is the same as ArrayList<? extends Object>.
> 
> ArrayList is similar to ArrayList but there are some differences. ArrayList is invariant while ArrayList is not.
> Eg:
> ` ArrayList<Object> foo = new ArrayList<Integer>();` flags compilation warning whereas `ArrayList<?> foo = new ArrayList<Integer>(); ` doesn't
> 
> Another differences is for ArrayList<?>, you can't call a method that depends on the actual argument passed because `? `lets you pass in anything that at runtime, we don't what is actually passed. At most, you can only call method s that doesn't depend on the actual argument passed like `clear() `method of ArrayList or some method inherited from Object like `toString() `(since we know everything is a subtype of Object).
> 
> Eg: Try
> `ArrayList<?> foo = new ArrayList<Integer>()`
> ` foo.add(2);`
> 
> You'll get an error

Thank you for the detailed explanation. It was very insightful
