### ISSUE TITLE
Cyclic Dependencies from Server class

### ISSUE THREAD

**Issue by yuyitan** [nus-cs2030/2021-s2#101]
I have been working on the project for several days and tried out a few different ways of approaching the question. From what I tested, I found out that Codecrunch rejects 'instanceof' and Cyclic Dependencies. Any code detected to have those will automatically be marked as fail. However, I cannot figure out why having a Server class with an Optional Customer inside gets marked as a cyclic dependency on Codecrunch. My Customer class does not have a Server. 

From my understanding, this should be allowed and not be marked as a cyclic dependency since it's only one-way.

Did anyone encounter the same issue? And if so, what did you do about it? Thanks!

**Comment by g4ryy** [comment]
Hello, could it be that your Customer class has a method that takes in a Server?

**Comment by ShyamalSankar** [comment]
Does your customer class mention server anywhere? Can be inside a method or an attribute

**Comment by OuaisBien** [comment]
do the cyclic dependencies exist only between your customer and server?

**Comment by yuyitan** [comment]
Hi, thanks for the replies. Yes, my Customer class has a method take takes in an array of servers. I did not know that this counts as a cyclic dependency since it is not in the constructor.

**Comment by E0540022** [comment]
I found this on [code crunch](https://stackoverflow.com/questions/3646113/circular-dependency-in-java-classes) :
The constructor of your class A calls the constructor of class B. The constructor of class B calls the constructor of class A. You have an infinite recursion call, that's why you end up having a StackOverflowError.

Java supports having circular dependencies between classes, the problem here is only related to constructors calling each others.

You can try with something like:

A a = new A();
B b = new B();

a.setB(b);
b.setA(a);


If code crunch does not state where is the line where they detect cyclic dependency, you may need to check not only server and customer class, perhaps the event class as well? Perhaps looking at private final of the classes may also help you find the error?

**Comment by Xeph-o** [comment]
> Hi, thanks for the replies. Yes, my Customer class has a method that takes in an array of servers. I did not know that this counts as a cyclic dependency since it is not in the constructor.

You can approach this question with your server taking an array / queue arraylist of waiting customer instead. Your customer and server should both be tied together via your event class.
