### ISSUE TITLE
How do you solve level 2 queue 

### ISSUE THREAD

**Issue by jeremycte** [nus-cs2030/2021-s2#107]
# Summary
Can't seem to solve the final test case of level 2 due to queue error. Below is the right output
![image](https://user-images.githubusercontent.com/44341818/112600941-c80ebd80-8e4c-11eb-99b3-987ccc5eacdf.png)

## Description 
Server serves the 2 customer simulteously when it's not supposed to. The right output is shown above.

## Screenshots (if any): 
![cs2030](https://user-images.githubusercontent.com/44341818/112600542-4e76cf80-8e4c-11eb-9367-6624b9c9de94.png)
![image](https://user-images.githubusercontent.com/44341818/112601086-fab8b600-8e4c-11eb-92af-42fea3845e79.png)

Hi, this is my level 2 project output for the final test case where the first 3 test cases, my code passed however for my last test case output seems to simulteously serve the Customer 9 & 10 without checking. Any hints/guides on how to solve this issue?

**Comment by Qingyi1115** [comment]
I think your server 1 status didn't update to "Occupied" after customer 9 start been served. 
Can try check on your serve event and wait event class

**Comment by gwajoon** [comment]
Hi jeremycte, I faced a similar issue when I was doing level 2 as well. The issue is probably that your servers' nextAvailableTime is probably  not updated whenever they have a waiting customer, hence you may want to look at your arrival and waiting event. You have to make sure that their nextavailable time takes into account the waiting customer and the time after the server is done serving that particular waiting customer

**Comment by Onelayer** [comment]
I encountered the same problem when I was doing level 2. The problem is that your current method to get serve time for everyone in the queue is taking the ending time of the one getting served(Customer 7 in this case). This result in your customer 9 and 10 getting the same served time and hence the priority queue will serve them both together. What you can do is trying to loop through the timing to ensure that each person in the queue gets the ending time of the person before the queue to prevent this issue.

**Comment by chengjiangg** [comment]
I encountered the same problem too. What I did was to add the Customer's service time into the Server's next available time whenever I add the Customer into the Server's wait queue. Then to get the serve time, take the Server's next available time and subtract the Customer's service time.

**Comment by ashleyleerx** [comment]
Hi I faced the same issues too. I think the issue may be your Done class or your Server class depending where the updateTime method is stored.  In this case, the time for customer 10 isn't updated properly. Hence when you update the time, you would need to take into account your currentServing.  Also, there could be a possibility that there could be issues with the Arrive class since both customers 9 and 10 are served at the same time, maybe because the  currentServing wasn't updated to customer 9

**Comment by KevinTan1203** [comment]
Hi, I've also faced the similar issue at first. After spending almost 2 hours trying to debug the code, one possible reason why you may be facing that is because you may not have successfully updated the general server state in your server array (in other words, I believed you tried to bring forward your waiting time and put it into the server, but since another event arrives and checks that server, the timing may not have been updated for that particular event, and thus, the latter event gets served as well. 

One way to see it is print your Priority Queue using System.out.println(YourPriorityQueueName); to see the state of the queue in each iteration. It really helps in the debugging process!

**Comment by chinjuanlee** [comment]
Hi, I've also faced similar issues like this, for me it managed to worked because I didn't update my next available time correctly which caused the problem. Maybe you can print out the server's next available time to try and debug the problem, because that helped me visualize the problem.

**Comment by jeremycte** [comment]
Thank you all for your amazing comments! Have managed to solved the issue with all your recommendations. Appreciate it! 😃

**Comment by wentinggy** [comment]
> I encountered the same problem too. What I did was to add the Customer's service time into the Server's next available time whenever I add the Customer into the Server's wait queue. Then to get the serve time, take the Server's next available time and subtract the Customer's service time.

hi! i tried this method and it works for my level 2 however it does not work for my level 1. how did you overcome this problem?
