### ISSUE TITLE
IntStream and Stream

### ISSUE THREAD

**Issue by eltonngkk** [nus-cs2030/2021-s2#108]
What is the difference between ```IntStream``` and ```Stream<Integer>```? How does the difference relate to performance(memory)?

**Comment by mltnsia** [comment]
IntStream is a stream of primitive int values.

Stream<Integer> is a stream of Integer objects.

**Comment by High325** [comment]
```IntStream``` has methods such as ```min()``` and ```max()``` that are more specific for usage on ints than the methods in ```Stream<Integer>```. This is not to say that it would not be possible to create a method that would find the minimum and maximum values of a ```Stream<Integer>```, but it is easier to use an IntStream if you already know that the type of the stream is int.

**Comment by karintang** [comment]
Boxing and unboxing do take some time, but it's not a lot. A lot of temporary boxed objects also triggers Garbage Collection a lot more often, and that's a performance drain too. It all adds up, so if the stream processes a lot of integer values in a tight "loop", the difference can be relevant.

The bigger problem is space since the overhead of the Integer is quite large. An int is 4 bytes for the value, while an Integer is 4 bytes for the reference plus 16 bytes for the object, so Integer uses 20 bytes per value, i.e. 5 times the memory.

This is especially relevant if you call toArray(), since there's a big difference between an int[] and an Integer[], space-wise.

**Comment by karintang** [comment]
Boxing and unboxing do take some time, but it's not a lot.

This is especially so if you call toArray(), since there's a huge difference between an int[] and an Integer[], space-wise.

**Comment by joeyylow** [comment]
When you use IntStream you are restricting yourself to be working with Integers. Using Stream instead provides more flexibility (also evident from the greater number of methods the Stream Interface has).

**Comment by yx0555** [comment]
Using IntStream is more specific to the primitive type Int and can be created using built-in methods like range() and rangeClosed(), as well as use more specific arithmetic operations such as sum(), min() and max(). To convert primitive values to their wrapper class you will have to use the boxed() method

**Comment by Keithlimhs** [comment]
Hi IntStream basically contains the primitive int, while Stream< T > can be called with other objects. Stream< T > can contain a stream of classes with the .stream() method called from a list of classes, while IntStream is only restricted to integers and hence do not have the .stream() method. However, IntStream have additional methods that are specific to integers. You can check out the Stream and IntStream API for the different methods
