### ISSUE TITLE
Private Access in Optional

### ISSUE THREAD

**Issue by TMTM98** [nus-cs2030/2021-s2#109]
# Summary

Description of the question / problem here.

Unable to use methods of Optional.

## Description:

Clarifications or details with respect to the issue you are facing

Why are the methods isPresent() and isEmpty() private access in Optional?

## Code Snippets

Attach code snippets (if any)

Main.java:21: error: isEmpty() has private access in Optional
            if (roster.get(name).isEmpty()) {
                                ^
Main.java:26: error: isEmpty() has private access in Optional
            if (roster.get(name).flatMap(x -> x.get(mod)).isEmpty()) {
                                                         ^
Roster.java:62: error: cannot find symbol
        if (mod.isPresent() == true) {
               ^
  symbol:   method isPresent()
  location: variable mod of type Optional<Module>
Roster.java:64: error: cannot find symbol
            if (ass.isPresent() == true) {
                   ^
  symbol:   method isPresent()
  location: variable ass of type Optional<Assessment>
4 errors

## Screenshots

Screenshots (if any)

**Comment by Zekeseoj** [comment]
I may be wrong but I dont think you are supposed to use isPresent nor isEmpty for codecrunch.

**Comment by KingRyo13** [comment]
Not sure about the private access thing, but if I'm not wrong the point of using Optionals is so you can manage possible null values with methods from the Optional class itself. 

I think you should redesign your Main class and instead of using if and else statements and using `isPresent()` or `isEmpty()`, you should use `ifPresentOrElse(Consumer c, Runnable r)`

This takes a consumer to perform an action with that value if its not null, or perform another runnable action if it is.

So you can write your entire input in one line, chaining a few `isPresentOrElse` methods.

**Comment by rljw** [comment]
Checking for `isPresent()` or `ifEmpty()` will not be acceptable by codecrunch, as it goes against the reasons for using Optionals in the first place. The private access error is interesting, because Optional methods should have public access by default, and when I try printing out `roster.get(name).isEmpty()` in my code it works without a compile error. Not sure if the error may have occurred due to the way you defined your class? Would you get the same error using the ifPresentOrElse method instead?

**Comment by jedkk** [comment]
The first 2 errors happened probably because of how you defined the get method.
The last 2 errors happened because "mod" and "ass" are not of type Optional, hence "isPresent()" and "is Empty()" do not exist.
It is okay to do your own checking with "isPresent()" and "is Empty()" (just like how you would print out lines to see output), but then they go against the use of Optional as mentioned by prof, so please throw them away before you submit the final codes.
