### ISSUE TITLE
[Lab 7 Level 5] Possible to use Streams?

### ISSUE THREAD

**Issue by yuyitan** [nus-cs2030/2021-s2#150]
I did Level 5 using the standard loop methods, but just curious if anyone managed to solve it using streams instead. I tried to use an IntStream for the sum(int n) method but I would not get the full log printout. I also realised that I cannot mutate the Logger inside the stream as variables has to be explicitly/effectively final.

**Comment by markwty** [comment]
You can create a Pair class containing the Logger and an integer and use it for a stream to iterate the integer from 1 to n while adding your Logger to the integer at each step.

**Comment by JasonDeKhanh** [comment]
Yea I managed to solve level 5 using streams

for the sum method I tried to create a streams of all the relevant integers (using iterate(, and then slowly add all those integers up using .reduce with a Logger as the identity (I used the reduce method with accumulator and combiner)

for the f method I did something similar, you just have to use your conditionals carefully when iterating to get all the correct integers in the stream.

**Comment by laitzheng** [comment]
@JasonDeKhanh Hi Jason, thanks for your helpful advice! May I know what the purpose of the combiner is in your reduce function?

**Comment by JasonDeKhanh** [comment]
oh actually I think that the combiner has no purpose here since we're only using a sequential stream. I just tried to put in a valid lambda but it wouldn't matter at all in this case. I use the 3-argument reduce method because it takes in a bifunction for the accumulator, allowing me to reduce all the Integer stream elements into a Logger.

**Comment by AdelineWongg** [comment]
@JasonDeKhanh may I know what is the combiner? Isit possible to do this with a 2-argument reduce?
I tried doing 
IntStream.range(1,n).reduce(Logger.make(0), (a,b)-> add(a,b))
but I will encounter errors.. not very sure why

**Comment by JasonDeKhanh** [comment]
@AdelineWongg the error here is because with a 2-argumet reduce, the accumulator you're taking in is a Function<U, U>. In short, your a and b must be the same type and then the output is the same type as well. I think that you're encountering errors because your a is a Logger (from identity) while your b is an Integer (from the stream). 

The reason I used the 3-argument is because the accumulator for that is in the form of a BiFunction, which allows me to pass in 2 objects of 2 different types and then it will return another type (can be either of the input type also). So with a BiFunction, you can take in a Logger and an Integer and then do something to them to return a Logger, for instance.
The combiner can literally be anything valid haha. I just put ((x, y) -> y). A combiner will only matter if you are using parallel streams (think prof mentioned in lecture 12 also at some point).
