### ISSUE TITLE
Lab 07 Level 4

### ISSUE THREAD

**Issue by kexinnnwang** [nus-cs2030/2021-s2#177]
# Summary
Logger.make(5).flatMap(x -> Logger.make(x)).printlog()

## Description:
I am not sure why .printlog() in this case only returns
 Value initialized. Value = 5 
and not 
Value initialized. Value = 5 
Value unchanged. Value = 5

Does that mean that .flatMap(x -> Logger.make(x)) has no effect on the logger?

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by eltonngkk** [comment]
Hi, I believe the  ```.flatMap(x -> Logger.make(x))``` here only has the effect of wrapping a new Logger around your current value and is a repeating action. Hence, it should not make a difference to your logs since there is no actual mapping conducted. Thus, to get the correct log output, you should consider creating a new log for each flatMap operation, remove the first message in this log, and then add the rest of the other logs into your current log. Hope this helps!

**Comment by kexinnnwang** [comment]
Ahhh I see thank you! @eltonngkk
