### ISSUE TITLE
Project Level4_3 issue

### ISSUE THREAD

**Issue by KaveenE** [nus-cs2030/2021-s2#198]
# Summary
Codecrunch test case 4.3 wrong output

## Description 
This is my thought process:

1. Is my executing of `ArriveEvent()` correct? 

2. Is my implementation of `ServerRest` and `ServerBack` somewhere wrong such that when I execute `ArriveEvent()`, it gives false positive `"isResting"` which causes the above error where my events/servers are ahead by 1(ie instead of "waits", its "leaves" or instead of `"Server 1, it's server 2"`
 -My `DoneEvent` updates the Server's resting time(if any), the server array etc, and then executes `ServerRest` 
 -My  `ServerRest` simply executes  to `ServerBack`.
 -My `ServerBack` unrests the server(ie sets restTime = 0) and that's it.

3. I think this where my problem may lie but I'm not too sure: My priority queue may have events of the same timing with the same server simultaneously in the queue. For example: `"ServerBack for server 1 at 14.55.."` and `"ServeEvent for server 1 at 14.55"` 

Could anyone provide any insight or something? Thank you
## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/59110376/114264313-a8ff5680-9a1c-11eb-9ed0-ad5f869bb9dd.png)

**Comment by Zekeseoj** [comment]
can I clarify if before implementing server rest and back events, what is ur done event responsible for ? For example, if your done event was originally supposed to update queueLength for a specific server, if you implement with server rest and back, the process of the done event should be 'halted' too right? i.e the event should update new event time but not execute the process at that point. because it has not 'finished' its done event yet.

**Comment by KaveenE** [comment]
Yup, my `DoneEvent` does update the server's queue too(i.e. dequeues the customer it has served)! Hmmm, I'm not quite sure what you mean, do you mean this updating of the queue should not be implemented in `DoneEvent`? 

But shouldn't you update it because this is how I see the flow: `DoneEvent`->`After serving, dequeue customer and update server's resting time`->Return `ServerRest`.

**Comment by Zekeseoj** [comment]
My bad, looking at your error, it seems that server 1 'disappears' after serving customer 9.  I believe that server 1 is resting when 13 arrives. Your code seems to prevents your arriving customers from queueing for server 1, which is probably the reason why your output does not show any server 1 records.

To explain what i mean earlier, consider this in real time terms,
-if our servers has no rest times, the moment they finished serving a customer, they would be ready to serve the next in line (waiting customer). *this would update the queueing situation for the server.*

-With rest times, if a server decides to rest the moment they finish serving their customer, the waiting customers will stay as they are. *queue will not be updated*
the resting server will then pick up its work once they are ready. *immediately serve first waiting customer + update queueing situation for the server again*

However, it seems like your issue does not lie with the process above because your server queues does not accept any potential waiting customers which is strange. Try to pinpoint why this issue occurs in your code. good luck!

**Comment by KaveenE** [comment]
> -if our servers has no rest times, the moment they finished serving a customer, they would be ready to serve the next in line (waiting customer). this would update the queueing situation for the server

I think this may be a potential source of error  for my program since my `ServeEvent `, `WaitEvent` timings may not change when the server is resting,

As for why my Server 1 is skipping out on work, I have to figure it out

Thanks for the help!

**Comment by eryuanren** [comment]
The maximum number of customers that can be in a queue is referring to the number of customers that can be waiting for a server, regardless if they are waiting for a customer to be done serving or a server to be done resting. That could be why 13 leaves instead of waiting.

**Comment by hypernuggets** [comment]
Hi, I had the exact same output issue, this is what I did to fix it (if you haven't done so already):

Check how your server's availability is registered and make sure that queue length refers to the number of customers **waiting** in the queue, not how many customers are actually **in** the queue. 

Eg. let max Queue Length be 2 - Meaning that if the server is currently serving a customer, you can have 3 total customers at that server, but if the server is resting, then you can only have a maximum of 2 customers waiting in the queue.

Also make sure that your Done event is correctly clearing out your queue!

**Comment by KaveenE** [comment]
Oh yes, thank you! @eryuanren  and @hypernuggets , that solved my issue but another popped up
