### ISSUE TITLE
 Stream.of  -vs-   IntStream.of

### ISSUE THREAD

**Issue by changjianxiang** [nus-cs2030/2021-s2#209]
I have been struggling to understand the difference between Stream.of  and also IntStream.of
![image](https://user-images.githubusercontent.com/77479126/114405996-c0d00980-9bd9-11eb-9916-db115be3e1d0.png)
![image](https://user-images.githubusercontent.com/77479126/114406085-d3e2d980-9bd9-11eb-8a55-fb43c7fcaa23.png)

The above 2 of method seem to be similar just that one takes in T... values while the other takes in int... values

However, when I pass in an array into the of method, the outcome turns out to be different as seen below:
![image](https://user-images.githubusercontent.com/77479126/114406421-1b696580-9bda-11eb-8f38-493594caf4fe.png)

Although both of method in Stream and IntStream seems to be similar in the JAVA API, the outcome turns out to be different so I'm quite confused as to why this is so.....

**Comment by Pchrome** [comment]
int[] stream cannot be auto casted into Integer[] array so stream.(arr) will absorb the entire array as a whole and the resulting count will be 1.

If the below is done,
Integer[] arr = new Integer[]{1,2,3,4}, then stream.of(arr).count() will be 4.

**Comment by tshuenhau** [comment]
`Stream.of(arr).count()` actually calls the of method that takes in 1 argument (`static <T> Stream<T> of​(T t)`) since `arr` is one array object. Therefore you have created a stream of int[] and this stream has 1 int[] element inside.

`IntStream.of(arr).count()` on the other hand calls the `static IntStream of(int... values)` method since an IntStream knows that its elements are Integers and not int[] , it will convert arr into its values.

**Comment by changjianxiang** [comment]
Thanks alot for the help!
