### ISSUE TITLE
ArrayList and Types

### ISSUE THREAD

**Issue by Pchrome** [nus-cs2030/2021-s2#210]
Background Info

Class A {
}

Class B extends A {

    public int getInt() {
        return 1;
    }
}

Hi all, here is the problem i am facing. 
So i have created: 
ArrayList<A> arr = new ArrayList<A>();
and  then an object of class B: 
B bobj = new B();

Afterwards i did:
arr.add(bobj);

After that i used get(), arr.get(0).getInt();
And i got an error which states that the function 'getInt()' does not exist.
May i know why is this the case although the method was defined in class B?

Thank you.

**Comment by g4ryy** [comment]
Hi, I believe it has to do with the way you initialised the array list. It should be:

ArrayList<B> arr = new ArrayList<>();

**Comment by changjianxiang** [comment]
Hi Pchrome, 

I went to input your code into Jshell. Perhaps is this what you are asking? Is it that when we create an ArrayList of type A(super class), we are still able to put type B(subclass) into the arraylist but you get an error when trying to do further operations on the element in the ArrayList?


![image](https://user-images.githubusercontent.com/77479126/114495239-50b09a80-9c50-11eb-8c3e-6ea592740acc.png)

This is because when bObj is placed into the arrayList<A>, only the "A" aspect of bObj is being captured in the arrayList (since the arrayList can only store type A stuff). Therefore, you can still placed bObj inside the arraylist since its a subclass of type A, but when you extract it out, only the "A" aspect of bObj is there, hence it cannot run getInt() method since class A do not have the method.

Hopefully this helps! and hopefully I'm not wrong :)

**Comment by Pchrome** [comment]
Thanks alot guys for your inputs i think i understand the issue
