### ISSUE TITLE
Project Cyclic Dependency Issues

### ISSUE THREAD

**Issue by rendao1010** [nus-cs2030/2021-s2#215]
# Summary
Hi, I'm at Level 3 of the project and it has suddenly dawned on me that it would be a good idea to submit my code to CodeCrunch to see if there are any issues. However, my code was flagged up for cyclic dependency issues. Do you guys have any tips on how to go about solving the issue? 

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/64304450/114671525-c68f3180-9d36-11eb-9ae4-c45654f1494b.png)

**Comment by suyatinglaura** [comment]
Hi, it seems that your Customer and Server classes are cyclically dependent on each other (one class uses the other). I'm not sure about your implementation, but you may try to let only Customer dependent on Server or Server dependent on Customer. Personally I would recommend the first way (only allow Customer depending on Server).

**Comment by dumbasssoul** [comment]
For me, I implemented Server has a customer (and customer queue waiting), while my Customer only consist of its id and service time

**Comment by ShyamalSankar** [comment]
Hello cyclic dependencies arise because A depends on B and B depends on A. In you case maybe Arrive class depends on Customer (stored as a variable or is a return type for a method or mentioned anywhere within the class) and vice versa. You should plan out the dependencies before proceeding. Ie if your server has a queue of Customers then your customer class cannot have any mention of the Server class.

Personally my Server depends on Customer. 
As for the events, if your event is dependent on Customer (ie has a Customer as an attribute, return type or mentioned anywhere) then the Customer should not have any single mention of the Event class. 
Hope this helps!

**Comment by rendao1010** [comment]
Thank you everyone! I have since resolved the issue in my code :-)

**Comment by arnav0401** [comment]
Dear RenDao,
I hope you have been able to solve this Cyclical Dependency :)

Best Regards,
!Chiau Ren Dao
