### ISSUE TITLE
CompletableFuture

### ISSUE THREAD

**Issue by salteefish** [nus-cs2030/2021-s2#261]
# Description

Hi, i do not understand why the answer for this question is D (i, ii, iv). I thought that the possible outputs would be 123 or 132 but i don't get why 1 need not necessarily be printed. This question was taken from AY201718 Semester 1 final assessment. Can anyone explain this to me please? Much appreciated.

## Topic:

CompletableFuture

## Screenshots
![Screenshot 2021-04-19 175510 (2)](https://user-images.githubusercontent.com/77676099/115270812-4837f280-a16f-11eb-89fd-2a9ba00d4d20.png)

**Comment by OuaisBien** [comment]
Maybe its because 1 will (probably) be printed after an undetermined amount of time. However, as soon as printAsync(2) and printAsync(3) finish, a new `CompletableFuture` will be returned, after which 1 will never be printed.

**Comment by elitanzc** [comment]
Hello! I think this happens when printAsync(1) takes longer to complete than printAsync(2) and printAsync(3). The line printAsync(1) immediately returns a CompletableFuture, but the second line of code in main requires both printAsync(2) and printAsync(3) to be completed before returning void. So after the second line of code completes executing, only 2 and 3 will be printed and the main method finishes its job and closes without waiting for printAsync(1) to complete.

**Comment by danieltwh** [comment]
Hey, the reason that 2 and 3 will definitely be printed is because of the .join() call on printAsync(2) and printAsync(3), where we wait for the two CompletableFuture to complete and return the value (in this case both do not return anything). However, .join() is not called for printAsync(1) so the programme does not necessarily need to wait for printAsync(1) to complete and may exit while printAsync(1) is still running/evaluating (haven't print out 1 yet).

Also, I think 213 and 312 are also possible outcomes because we are not sure how long printAsync(2) and printAsync(3)  will take. Hope this helps! :)

**Comment by salteefish** [comment]
Thanks everyone for the explanation, I think i'm starting to get it now!

**Comment by itsjiaming** [comment]
Insightful question, thanks for asking salteefish!

**Comment by salteefish** [comment]
No problem itsjiaming! Glad everyone could learn
