### ISSUE TITLE
Not sure where exactly is the error for testcase 5_4

### ISSUE THREAD

**Issue by isaactyj** [nus-cs2030/2021-s2#264]
# Summary
Put a summary of the question

## Description 
I am unsure what exactly is the testcase but somehow in my implementation, number 9 suddenly goes to be served by server 4

## Screenshots (if any): 
![wrong](https://user-images.githubusercontent.com/77622789/115341854-e2358480-a1db-11eb-9120-fff634799e19.JPG)

**Comment by gracefour11** [comment]
i can think of a few problems that could've happened:
1. service duration for 9 in your implementation is different from the service duration in the test case 5_4. You can verify this by manually annotating for your implementation and compare w the testcase.
2. maybe 9 is not supposed to be greedy, i.e. 9 may not be greedy in the test case 5_4.

**Comment by gracefour11** [comment]
I'd start by checking how 8 didnt stop serving by 1.152 as shown in the test case at line 30.

**Comment by rendao1010** [comment]
I had the same issue that you did, if I had to guess you pre-generated the service times for all your customers before the simulation. The error in this (as pointed out in the last line of the level) is that the _n_th customer to arrive may not be the _n_th customer to be served, and so you have to figure out a way to generate the service time only when the serve event for that respective customer is scheduled. (The hint given in the level is to use lazy evaluation!)

**Comment by isaactyj** [comment]
@rendao1010 By that, can i guess that you pass everything into the simulator then from there it will generate the customer inside one at a time?

**Comment by rendao1010** [comment]
The way I implemented it was via wrapping the RandomGenerator.genServiceTime() in a Supplier, then passing that Supplier into my Customer class. When the Serve event is generated, I will then call the get method of the Supplier to generate the Service Time. 

However, do be careful to make sure that you do not call the get method of the Supplier prematurely (in other classes), and also after calling it you should cache the value so that if you do need the serviceTime of the Customer subsequently, you do not generate it via the RandomGenerator but rather use the value that you have already generated previously. Hope this helps!
