### ISSUE TITLE
Level 5 Test case 11

### ISSUE THREAD

**Issue by Deshun99** [nus-cs2030/2021-s2#271]
Encountered a difference in expected vs actual output (as shown below). Could the error be due to the fact that the server's queue length is incorrect?

## Screenshots (if any): 
Insert Images here if necessary
![Untitled](https://user-images.githubusercontent.com/77624433/115409769-a377ec80-a224-11eb-9fb1-ac75f62454ce.png)

**Comment by eryuanren** [comment]
You might want to check your logic for how a greedy customer chooses the server. Maybe your comparator as well to see if it is choosing the server with the lowest index given the same length of queue

**Comment by KevinTan1203** [comment]
This seems like an unusual case to begin with. It could be due to your comparison of time between customers, or when your server is done serving a customer, it forgot to remove him/her just as when a new customer arrives. I believe for the comparison wise, if the timings are the same, then your sorting of events in the Priority Queue should be done base on the event numbers, which in this case arrive should take precedence first before done

**Comment by Deshun99** [comment]
Thanks @KevinTan1203 and @eryuanren I think my comparator was the cause of the issue as my sequence of event was initially arrive serve done and leave where it in fact should be the doneevent to be of highest priority
