### ISSUE TITLE
AY19/20 Sem 2 Polymorphism Output

### ISSUE THREAD

**Issue by yuyitan** [nus-cs2030/2021-s2#303]
Hi, I would like to check answers for this question to access my understanding of Polymorphism.
<img width="682" alt="Screen Shot 2021-04-22 at 8 27 57 PM" src="https://user-images.githubusercontent.com/77650951/115714014-3d68a200-a3a9-11eb-8940-30233384507a.png">
foo) 1555

<img width="676" alt="Screen Shot 2021-04-22 at 8 28 27 PM" src="https://user-images.githubusercontent.com/77650951/115714062-4ce7eb00-a3a9-11eb-97ac-e7af43a0eaa2.png">
bar) 5251

<img width="700" alt="Screen Shot 2021-04-22 at 8 28 38 PM" src="https://user-images.githubusercontent.com/77650951/115714083-52ddcc00-a3a9-11eb-89c1-73689b4eddc4.png">
baz) 5515

**Comment by eseutella** [comment]
Hello I got foo 1534, bar 3131 and baz 5313. My reasoning is around the same for all of them. For example, under foo, I got 3 for b.foo(ab) because b is of Type B hence the foo method will be from class B. As foo takes in an ab which is of Type A, the method used is foo(A a) hence 3 will be printed. 

I am not sure for this but another example is under bar, I got 3 for i.bar(y) because i is of Type I1 and it takes in a y of Type Y. However, there is no method in interface I1 that takes in bar(Y y) hence bar(X x) will be used instead and the class will be in class Y since I1 i = new Y(), thus printing 3.

**Comment by ivankqw** [comment]
> Hello I got foo 1534, bar 3131 and baz 5313. My reasoning is around the same for all of them. For example, under foo, I got 3 for b.foo(ab) because b is of Type B hence the foo method will be from class B. As foo takes in an ab which is of Type A, the method used is foo(A a) hence 3 will be printed.
> 
> I am not sure for this but another example is under bar, I got 3 for i.bar(y) because i is of Type I1 and it takes in a y of Type Y. However, there is no method in interface I1 that takes in bar(Y y) hence bar(X x) will be used instead and the class will be in class Y since I1 i = new Y(), thus printing 3.

for i.bar(y), I think the explanation will be like this: i of compile time type I, runtime type of Y. Since dynamic binding occurs we can only think of overriding methods. i with the behaviour of Y executes overriding method bar(X x), since y is substitutable for x.  3 is printed.

**Comment by karintang** [comment]
Hello, 
foo: 
1
5
3 (ab is of Type A)
4 

bar:
3 (no method in interface I1 takes in bar(Y y) hence bar(X x) will be called in class Y since Y is the sub class of X and the runtime type for I is Y)
1 (Y is the sub class of X)
3 (XY is of type x)
1 

baz: 
5 
3 (pq is of type P)
1
3 (I do not have a method for baz(Q q). Since q is the sub type of P, baz(P p) will be called)

**Comment by gableejh** [comment]
i got 
1534
5131
5315

**Comment by yuyitan** [comment]
> Hello,
> foo:
> 1
> 5
> 3 (ab is of Type A)
> 4
> 
> bar:
> 3 (no method in interface I1 takes in bar(Y y) hence bar(X x) will be called in class Y since Y is the subclass of X and the runtime type for I is Y)
> 1 (Y is the subclass of X)
> 3 (XY is of type x)
> 1
> 
> baz:
> 5
> 3 (pq is of type P)
> 1
> 3 (I do not have a method for baz(Q q). Since q is the subtype of P, baz(P p) will be called)

Thanks so much for your explanation! Very clear and concise :D

**Comment by clementyee303** [comment]
@karintang 
> 3 (ab is of Type A)

May I just add on - ab has a _compile-time_ type A, which is why the overloaded method `foo(A a)` is called. However, if you were to call ab.foo(a),  it would print 3 instead of 1, as the _run-time_ type of ab is actually type B (the overridden foo(A a) method in class B extends A will be called instead)

**Comment by wenshienyap** [comment]
> Hello,
> foo:
> 1
> 5
> 3 (ab is of Type A)
> 4
> 
> bar:
> 3 (no method in interface I1 takes in bar(Y y) hence bar(X x) will be called in class Y since Y is the subclass of X and the runtime type for I is Y)
> 1 (Y is the subclass of X)
> 3 (XY is of type x)
> 1
> 
> baz:
> 5
> 3 (pq is of type P)
> 1
> 3 (I do not have a method for baz(Q q). Since q is the subtype of P, baz(P p) will be called)

Hi @karintang! How do you reason not calling baz(Q q) instead? since there's a method for that in class Q, and that object i is of type Q, and object q is of type Q?

**Comment by Herrekt** [comment]
Hi @wenshienyap. Since i in i.baz(q) is of Type I, it will only use methods included in the interface which does not have baz(Q q). So instead it uses baz(P p) as Q is a subtype of P and prints 3.

**Comment by dannytayjy** [comment]
My answers are:
1534
3131
5313

**Comment by Radix-huang** [comment]
Same answer:
1534
3131
5313
