### ISSUE TITLE
Cannot Find Symbol "RandomGenerator" (Project, Level 5)

### ISSUE THREAD

**Issue by chehoelau** [nus-cs2030/2021-s2#313]
# Summary
Can't find symbol RandomGenerator even though my java file is within the same package as RandomGenerator.
I've tried creating a test class called PublicGen.java, which includes the usage of RandomGenerator. However, there is still error. I have chmod 777 the file, but it is still throwing the same error. Anyone has any ideas?

My folder structure is as such:
```
cs2030
|--simulator
|--|--PublicGen.java
|--|--RandomGenerator.class
```

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/29771154/115925610-0206ca00-a4b4-11eb-9127-244c4dab25b6.png)
![image](https://user-images.githubusercontent.com/29771154/115925680-1f3b9880-a4b4-11eb-8520-870077b7d487.png)

**Comment by somenobody98** [comment]
Hi, I faced the same error when I tried to compile them in the folder cs2030/simulator itself. However, when I compiled them outside this folder, it works. Like my Main method was not in the folder, and when I compiled the Main method, there was no such error. So maybe you could try that?

**Comment by eugenechua94** [comment]
Hi, just to add on to what was mentioned above and what I've done and worked, though it might not be the most direct way- 

1. The random generator class belongs to a package named cs2030.simulator, and your other code aint, which is why they could interact with it (you can open the class file in intellij and check the class, it has the name "package cs2030.simulator: at the top.
2.  Following which, I created a sub folder named cs2030 within my project folder, and created another sub folder named simulator and put all my other classes, less the main class, and the random generator class within it. (this step might not be necessary, you can try it test it yourself) 
3. Add in the code "package cs2030.simulator" in all these classes within the folder to allow them to interact with the random generator. Make the class which with interact with the main classes public, and that involves the constructors as well.
4. Go back to your main classes, and include the code "import cs2030.simulator."specific class name you want to interact with*" 

Based on your design, you should be able to construct a random generator object within the classes of the same package, kand even the main class should you import it.

p.s. for troubleshooting you can consider creating a copy of randomgenerator class as java.

**Comment by ryantjx** [comment]
Hi, you should also add in the 4 methods that the Random Generator has so that it can be called via your PublicGen class.

**Comment by chehoelau** [comment]
Solved. Thanks guys! I managed to do it by placing `package cs2030.simulator;` on top of my .java files, but not placing the .java files inside the folder /cs2030/simulator. Compile it using `javac -d . JAVA_FILE.java` to have the class files automatically appear in the directory.
