### ISSUE TITLE
Rest Time how to implement

### ISSUE THREAD

**Issue by TMTM98** [nus-cs2030/2021-s2#344]
# Summary
Put a summary of the question
I have no idea how to implement the rest time without tying it to a customer.

## Description 
Describe the problem and code snippets if necessary 
Currently, I attached the rest time to the Customer class but that is clearly not correct. I tried making an array that contains all the rest time but I cannot seem to implement it properly in my Manager class. Any information on how the rest time should be implemented?

![image](https://user-images.githubusercontent.com/77833847/115991471-228d6c00-a5fb-11eb-8699-85a349d2e00b.png)

## Screenshots (if any): 
Insert Images here if necessary
The manager.service() function that implements the Queued events:
![image](https://user-images.githubusercontent.com/77833847/115991458-11445f80-a5fb-11eb-9ba4-e4b7ad5d10c5.png)

**Comment by stttaa0k** [comment]
Hi, you may want to consider passing the array of rest times into your next event function instead of individual rest times.  Do check out #239

**Comment by Deshun99** [comment]
Hi i think the rest time should be tied to a server instead as it is the server resting, do consider creating a RestEvent class for the server to rest.

**Comment by Reintang98** [comment]
Personally, I made rest an event just like arrive, wait etc. I actually did the same by putting all the rest times in an array that is created in a manager class. I only remove the rest time when there is a transition from Done to Rest. Hope this helps!

**Comment by rljw** [comment]
You can still tie the rest time to the Customer class in a way, just that you cannot assign the rest time at the beginning. What I did was to pass an array of rest times to my next event and create a RestEvent class, just like the others have mentioned above. Additionally, when a RestEvent is created, I will poll a rest time from the array and increment the time that the customer will be served by the amount of rest the server takes in the Customer class.

**Comment by tzerenchua** [comment]
To add on to the comments above, I stored my rest times as an ArrayList. One mistake I made when I was doing this question was that I associated the rest time with the customer ID but the rest times should be obtained from the order at which the customer has been finished serving (e.g: if customer 1 finishes first and customer 3 finishes being served before customer 2, the server who served customer 3 would have the rest time from the second position of the time array rather than the third).

In that regard, you would need a way to keep track of the number of customers who have been served - for this I had a void method in my simulator that increases the number of customers I serve by 1 every time I call it. Hope this helps!

**Comment by gableejh** [comment]
after a done event, check the list for the latest rest time to see if the server needs to rest. if yes, you can initiate a ServerRest event

**Comment by luthertan98** [comment]
For my implementation, i did a Rest event to store the timing of the Serving time of the next server so it can be passed on to the next Serve Event.
But the updating of the Server, i did it in my Done event before passing it to the Rest event.

**Comment by ARPspoofing** [comment]
> after a done event, check the list for the latest rest time to see if the server needs to rest. if yes, you can initiate a ServerRest event

how would you then make the waiting customers get served after rest? wouldnt there be cyclic dependency?

**Comment by luthertan98** [comment]
> > after a done event, check the list for the latest rest time to see if the server needs to rest. if yes, you can initiate a ServerRest event
> 
> how would you then make the waiting customers get served after rest? wouldnt there be cyclic dependency?

i think to avoid cyclic dependency you dont return the Serve in the Done event instead pass it on to the Rest event and if there is a rest event which you can detect using boolean or something in your Main/ manager and add in the Serve event and there will not be any cyclic dependency

**Comment by yx0555** [comment]
hello! I did a rest event to change the state of the server, and that rest event will be called in my Main class every time a Done Event is called. I did manage to implement using an arraylist, such that all my rest times are stored inside in the main method. Every time a rest event is called, I remove the first element from the array so as to maintain the correct order.

**Comment by tzerenchua** [comment]
> hello! I did a rest event to change the state of the server, and that rest event will be called in my Main class every time a Done Event is called. I did manage to implement using an arraylist, such that all my rest times are stored inside in the main method. Every time a rest event is called, I remove the first element from the array so as to maintain the correct order.

Just to offer another perspective, while I believe the rest event is useful, I don't think it's 100% necessary as I managed to implement my code without including this event. For me, my Server has a property CustomerServing (the current customer being served) so what I did was after a done event is executed, I set the CustomerServing to null. I then check whether the queue is non-empty, and then update my CustomerServing to the first person in the queue. 

However, I only removed the first person in the queue only when a serve event is executed to indicate that the customer is being served (for this, I had a boolean in the done event to check whether the queue is non-empty - since an incoming customer can either come immediately or come from the queue). Hope this might be of some help!
