### ISSUE TITLE
Project Level 5 Compiling

### ISSUE THREAD

**Issue by nicolaineo** [nus-cs2030/2021-s2#380]
Hi, can I get help with the compiling portion for my code. I know there has been several threads for it but I just can't seem to get it to work

These images will show my directories and the issue i face when trying to compile the code

THANKSSS

<img width="960" alt="2021-04-27 (9)" src="https://user-images.githubusercontent.com/77562513/116150183-a63b7b80-a715-11eb-8bd0-976f49382c4b.png">
<img width="960" alt="2021-04-27 (10)" src="https://user-images.githubusercontent.com/77562513/116150192-a8053f00-a715-11eb-9ff2-4c300ed6c957.png">
<img width="960" alt="2021-04-27 (12)" src="https://user-images.githubusercontent.com/77562513/116150193-a89dd580-a715-11eb-9907-368a94fc6e65.png">

**Comment by Hanyu0118** [comment]
You may try cs2030/*.java.

**Comment by gableejh** [comment]
try compiling with `javac -d . *.java`

**Comment by tzerenchua** [comment]
Hello, currently I see right now that your directory is at 2030>Proj. For me, what I did was placing my Main files in the 2030 directory, and also placing the cs2030>simulator file there. So in your case the order should be Desktop>2030>cs2030>simulator. The Main1 - Main5.java should also be in your 2030 directory (i.e Desktop>2030) 

As for compiling if you want to compile files in your simulator, just go to the Desktop>2030 directory and use javac cs2030/simulator/*.java to compile all your java files (can refer to issue #137). For main classes can just compile as per normal since Desktop>CS2030 is where your main classes reside. Hope this helps!
