### ISSUE TITLE
AY20/21 Sem1 Q6b

### ISSUE THREAD

**Issue by rljw** [nus-cs2030/2021-s2#386]
Hi, anyone had any comments for part (b)? I'm not too sure what is expected, as the stream seems to work fine

![image](https://user-images.githubusercontent.com/79345598/116212791-cac83f80-a777-11eb-92ed-c9d9dde1d31e.png)

**Comment by brendancjz** [comment]
Hi, the way this stream was constructed is flawed. This is because there are side effects in this stream, where s, a local variable outside of the lambda expression is being manipulated. But the stream works fine because the .forEach(x -> ...) method allows side effects to occur. A better way to construct the stream would be to use the reduce method. Hope this helps!

`int s = IntStream.range(1,100).boxed().reduce(0, (x,y) -> x + y);
s;`

**Comment by glennbjorn** [comment]
I did a similar method to @brendancjz. I thought that since the purpose of the stream was just to sum up integers 1 to 99, I didn't see a need to store the result. I also didn't see a need to box the IntStream, so I simply did:
`IntStream.range(1,100).reduce(0, (x,y) -> x + y)`

**Comment by Zekeseoj** [comment]
hello does anyone know how to do part e for this qn?
![1231](https://user-images.githubusercontent.com/77658282/116253076-bb122080-a7a2-11eb-930f-25ff122cb2e6.png)

**Comment by bandytan** [comment]
![image](https://user-images.githubusercontent.com/76738327/116253931-7e92f480-a7a3-11eb-9ec7-b442191f99ea.png)


I used this reduce method. The accumulator I used (x,y) -> x + y.length(), and the combiner u can just use (p,q) -> p to reduce the stream to the first element.

**Comment by glennbjorn** [comment]
> hello does anyone know how to do part e for this qn?
> ![1231](https://user-images.githubusercontent.com/77658282/116253076-bb122080-a7a2-11eb-930f-25ff122cb2e6.png)

Hi @Zekeseoj, what I did was add all the words into one line of string before calculating the length.
`reduce("", (x,y) -> x + y).length()`
It's an alternative solution that seems to get the answer, so hope this helps!
