### ISSUE TITLE
17/18 S2 Q4

### ISSUE THREAD

**Issue by KaveenE** [nus-cs2030/2021-s2#406]
# Summary
Type-erasure realated

## Description 
May I know why type-erasure occurs at compilation time only? 
Shouldn't it only occur at run time? 
If type was erased at compile-time, it defeats the whole purpose of using generics wouldn't it?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/59110376/116328100-d741ac00-a7fa-11eb-860e-1fb969685a6d.png)

**Comment by Atem729** [comment]
If I'm not wrong type erasure is not tested for our finals?

**Comment by brendancjz** [comment]
Type Erasure is not tested in this Finals. That is how the Java compiler work with Generics during compilation, it replaces the generic type with Object so that it can compile as it does not know what is <T>. But since it knows that all types extend Object, it erases the type and replace it with Object so that the code can be compiled.

**Comment by Buwoo** [comment]
The whole purpose of generics is to ensure type safety so the compiler doesnt bomb. During type erasure, the generic typing is replaced with the upper most bound <? extends Apple>, then after type erasure our object will have type Apple. In a similar vein, unbounded objects will take on Object type. Also in certain cases, the compiler may decide to create synthetic methods to differentiate between similar methods. Basically, its not as if "all is lost" when we do type erasure at compile time. Hope this helps.

**Comment by KaveenE** [comment]
I was just asking out of curiosity, thanks I got it now.
