### ISSUE TITLE
17/18 S2 Q5

### ISSUE THREAD

**Issue by KaveenE** [nus-cs2030/2021-s2#407]
## Description 
Shouldn't B be false since it doesn't obey the underlined sentence in the below picture?
`Eg: accumulator.apply(100,40) == 100 (and not 40)
`

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/59110376/116328948-bd08cd80-a7fc-11eb-887f-53b93df3df61.png)
![image](https://user-images.githubusercontent.com/59110376/116328920-a9f5fd80-a7fc-11eb-8087-2a8d9674ea1d.png)

**Comment by chooweixiang98** [comment]
![image](https://user-images.githubusercontent.com/26595217/116331356-2dfeb400-a802-11eb-8baf-55e43b13a86c.png)

**Comment by brendancjz** [comment]
It could be due to the .reduce method being the two argument type rather than the three argument type. In the two argument .reduce method, it uses BinaryOperator<T> instead of BiFunction<U, ? super T, U>. In the notes, accumulator.apply(identity, t) refers the the BiFunction<> one. So that could be the reason why it still works, though I am not very sure myself. Good catch though!

**Comment by KaveenE** [comment]
I tried it in jshell and was surprised, it gave consistent a output of 140.

Anyways, @brendancjz, unfortunately that that picture is based on this(ie applies for 2-argument reduce)
![image](https://user-images.githubusercontent.com/59110376/116334009-1544cd00-a807-11eb-9b53-e8d02bb22857.png)

**Comment by ireneliee** [comment]
I think what @brendancjz said is true.  It works because the reduce method used in the question above is the one that take sin identity and binary operator as parameter. Consistent output in parallel stream depends on whether the function is associative or not. So say that instead of Math.max(), you take in function a/b or a - b (which is not associative), the answer will be different each time (i think!)

**Comment by markwty** [comment]
The condition `accumulator.apply(identity, t)=t` will need to hold if the intention is simply to calculate the value of Math.max(x,y) across the elements of the stream. That is the original intended use for the reduce function as seen from the naming of first argument as identity which means it should not have any effect on the result of the accumulator like the identity matrix when multiplied with any other matrices.
For parallel operations, the most important and usually the only thing to consider is the associativity of the accumulator. Since the order which the results are accumulated/combined is hard to determine, to always produce the same result as in the sequential case, the function has to be associative.

**Comment by danieltwh** [comment]
Hi KaveenE, in this case, we have to think about the intention of why combiner.apply(identity, t) = t is a criteria for parallelizable reduce. The reason is because the combiner.apply(identity, t) will be done multiple times on each element in the stream. The number of times this is done is undeterminable. Hence, this criteria is there so that calling combiner multiple times will not interfere with the final results.

However, in this case, if all numbers are less than 100, then Math.max(100, ele) will always be 100. If there are any numbers greater than 100, then Math.max(100, ele) will always be the ele. No matter how many times combiner is called, the final result will still be the same. 

You can think of parallel streams a group of workers that randomly pick their numbers from the pool (stream). After they work on it a little (accumulate a little), they then want to combine their results. Calling Math.max(x, y) when they want to combine and when they are accumulating will give the same final result all the time.

**Comment by KaveenE** [comment]
Thanks guys, I think I've gotten the hang of it but could I just clarify this one thing which I have seemed to sort of inferred from your explanations: 
Is `accumulator.apply(identity, t) == t` and `combiner.apply(identity, t) == t` meant only for the elements of the original stream (ie from the data source)?

**Comment by danieltwh** [comment]
> Thanks guys, I think I've gotten the hang of it but could I just clarify this one thing which I have seemed to sort of inferred from your explanations:
> Is `accumulator.apply(identity, t) == t` and `combiner.apply(identity, t) == t` meant only for the elements of the original stream (ie from the data source)?

@KaveenE Hmmm not exactly. They should be true even when t is from another thread running in parallel. 

For example, the t in `combiner.apply(identity, t)` may be the result of the accumulator.apply(...,...). This explains why another criteria for parallelizable reduce is that `combiner.apply(u, accumulator.apply(identity, t))` must be equal to `accumulator.apply(u, t)`. 

I guess the idea behind the `.combiner.apply(identity, i) == t` is for consistency (ie not changing the results when applying combiner with the identity multiple times. The results could be from the data source or from another thread running in parallel)

**Comment by KaveenE** [comment]
Got it... sort of!
