### ISSUE TITLE
[Recitation 5] Cyclic dependencies

### ISSUE THREAD

**Issue by yuyitan** [nus-cs2030/2021-s2#45]
I submitted my code to Codecrunch and this is the first time I am encountering this error. I did a quick search and found that cyclic dependency refers to mutual dependency and it's generally frowned upon (aka bad). However, in real life, it logically makes sense for mutual dependency to occur (e.g. a Wife has a Husband and a Husband has a Wife). Why are cyclic dependencies considered harmful and how may one go about resolving this issue?

**Comment by raymondtanujaya** [comment]
If you think about it, to create Wife, you need an instance of Husband. Fine, you can create Husband first. However, creating Husband also requires Wife. With this dependency, you can't really create one of them at the first place.

Solution that I can think of for cyclic dependency is to use third person(class) to store the relation of those dependent class. So, for my example, instead of designing classes like Husband and Wife, I can stick to the class People, creating instances people1 and people2, and then create a class MarriageCertificate, containing info like who is the husband or the wife, that both people1 and people2 have as attribute(say that they are married then they hold the same instance of MarriageCertificate. CMIIW

**Comment by chooweixiang98** [comment]
From my understanding, breaking the cyclic dependency can improve modularity. In particular, it allows you to test components of your codes separately. It may be easy to correct errors in smaller projects that have cyclic dependencies, but that may not be the case for larger projects. Especially so for run-time errors.

**Comment by raymondtanujaya** [comment]
Hello, I think I just encountered this bug also. After some time, to break cyclic dependency, you can start from building a class that can run on its own given dummy input. You need to test it before using it e.g. the very first class should be tested only with primitives (String, int,etc). 

From then on, you can build another class that use the previous built class, and test it the same way as before. I think to further elaborate my last comment, the reason why this cyclic dependency happens is that we skip the testing part each time we build a class e.g. build 2/3 classes and test them altogether. This way, the cyclic dependency looks very subtle and in fact, it can compile for my case but can't detect the constructor of one of the class and hence fails in instantiating an object.

Ultimately, thinking about which class goes first to this  `jshell -q bottom_to_up_dependency.java` indeed is very worth if you are struggling to understand the cyclic dependency in your design.

**Comment by gableejh** [comment]
Not sure about real life, but in this module we shouldn't cyclic dependencies where two classes rely on each other. To resolve this, design your classes in a way where either A relies on B only or the other way round instead of it being both ways
