### ISSUE TITLE
Why does CodeCrunch not grade if variables are not declared private final?

### ISSUE THREAD

**Issue by chence08** [nus-cs2030/2021-s2#46]
Why is immutability such a big deal...

**Comment by E0540022** [comment]
There are a few reasons I found, here are the reasons,
1. Immutable objects are thread-safe so you will not have any synchronization issues.
2. Immutable objects are good Map keys and Set elements, since these typically do not change once created.
3. Immutability makes it easier to write, use and reason about the code (class invariant is established once and then unchanged)
4. Immutability makes it easier to parallelize your program as there are no conflicts among objects.
5. The internal state of your program will be consistent even if you have exceptions.
6. References to immutable objects can be cached as they are not going to change.

Personally I feel like we may not feel the importance of it here yet. Perhaps the habit of keeping classes immutable will help us out in the future?

Original source =
 https://www.linkedin.com/pulse/20140528113353-16837833-6-benefits-of-programming-with-immutable-objects-in-java#:~:text=Immutable%20objects%20are%20thread%2Dsafe,do%20not%20change%20once%20created.&text=Immutability%20makes%20it%20easier%20to%20parallelize%20your%20program,are%20no%20conflicts%20among%20objects.

**Comment by Keithlimhs** [comment]
I think that for this module we are forced to make our attributes private final to adhere to the OOP principles that we are though, like immutability and information hiding, in order to push us to create a better design for our classes

**Comment by yuyitan** [comment]
Immutability is emphasised as it is good practice to ensure that your variables do not accidentally get modified/overwritten somewhere in your code and you will always have the original values as per initialised. It will make life easier in terms of both debugging and retrieval of the data. The 'final' tag itself also helps to act as a 'safety net', we may not think we need it, but having it there, the compiler will give a compilation error and stop us from accidentally overwriting our variables which can be really helpful.

**Comment by saiyara1512** [comment]
Immutability is really to ensure attributes/variables are thread-safe so it can be passed around and nothing would change, it makes sure our values aren't overwritten. Also it's one of the OOP priniciples. I guess it's for a cleaner and better design that's not as prone to bugs!

**Comment by lokehsienjie** [comment]
Immutability will probably be very useful for us in the future when our projects get bigger and our code takes up thousands of lines, with many different user-created/implemented objects. If not for immutability, it would be like finding a needle in a haystack during debugging.
