### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by hewtungyuen** [nus-cs2030/2021-s2#61]
After watching the lecture, I am still unsure of when to use the wildcard operator. Could somebody explain it to me? Thank you!

**Comment by eryuanren** [comment]
We use it when we want to perform substitution in generics. We may not know what type our input might be so we use <?> to indicate any type. <? extends u> and <? super u> can also be used to narrow down the type that can be accepted.

**Comment by Onelayer** [comment]
To my understanding, wildcard is an unknown type. As different instantiation of a generic type are not compatible with one another, the wildcard is used to solve this.

There are a few types of wildcards, upper-bounded, lower-bounded and unbounded wildcards. You can check the link below which I used to understand more about wildcard. 

https://www.google.com.sg/amp/s/www.geeksforgeeks.org/wildcards-in-java/amp/

**Comment by dumbasssoul** [comment]
https://docs.oracle.com/javase/tutorial/java/generics/wildcards.html
found this really helpful in understanding wildcards, hope it helps!

**Comment by marvinljw** [comment]
https://stackoverflow.com/questions/16707340/when-to-use-wildcards-in-java-generics
Found this quite useful in explaining the different types of wildcards and when to use them in different situations. Wildcards are often used so that you can input any type that you want. To limit its "wildness", you can use bounds like what Onelayer and eryuanren have mentioned. Hope this helps! :)

**Comment by Atem729** [comment]
A<? extends T>  means that A can contain any subclass of T including T
A<? super T> means that A can contain any superclass of T including T

These are the 2 main wild cards explained in lecture. They are usually used to make our generics more general to more types. Hope it helps !

**Comment by cwh1999** [comment]
To my knowledge, wildcards types ? should be used when subtyping among generic types. ? is a notation to denote the variance of generic type.
 ? cannot be declared as a class but uses the extends and super keywords to specify the bound. 
If circle is a subclass of shape then List<Circle> and List<Shape> are subtypes of List<? extends Shape>.

**Comment by Keithlimhs** [comment]
From what i understand, wildcards are used to for substitution in generics, because substitution in generics is not as straightforward as substitution in arrays. For example, Shape[] shapes = Circle circles[] because circle is a sub-class of Shape, so there will not be an error doing substitution like this for arrays. However, since generics are invariant, we cannot perform substitution like how we would to an array. Hence, the wildcards ? come into play when we would like to substitute one generic to another

**Comment by hewtungyuen** [comment]
Thank you for the comments, they were very insightful!
