### ISSUE TITLE
List and ArrayList

### ISSUE THREAD

**Issue by eltonngkk** [nus-cs2030/2021-s2#65]
Hi! While trying to code Generics, I realised that ```List<String> list = new List<String>()``` will give an error
![image](https://user-images.githubusercontent.com/80501439/110972816-6273f900-8397-11eb-9a35-63a109969fc0.png)
while ```List<String> list = new ArrayList<String>()``` works. Can someone explain to me why I am able to instantiate a List this way?

**Comment by cwh1999** [comment]
Hi eltonngkk, the reason why the code above will return an error is because List is an interface according to the java API and being an interface, it cannot be instantiated. 
ArrayList is a class that implements List and thus would not produce an error. 
You can take a look at the API for all known implementing classes besides ArrayList for your reference, hope it helps! 
https://docs.oracle.com/javase/8/docs/api/java/util/List.html

**Comment by Atem729** [comment]
The reason is "List" itself is not a class in Java, similar to "Map". When instantiating a "List" or "Map" we use "new ArrrayList" and "new HashMap" accordingly.

**Comment by gableejh** [comment]
If I'm not wrong, it's because list is an interface and thus, one cannnot directly instantiate it.

**Comment by Keithlimhs** [comment]
List is an interface and hence it cannot be instantiated like a concrete class. ArrayList is a concrete class that implements List and hence should be used for instantiation instead
